# Usage:
# make        # compile all binary
# make clean  # remove ALL binaries and objects

.PHONY = all clean

CC = g++			# compiler to use


all: compile

compile:
	g++ cyk_main.cpp g_rules.cpp

clean:
	rm a.out
